### ISSUE TITLE
dtc source

### ISSUE THREAD

**Issue by 007revad** [PeterSuh-Q3/tcrp-addons#4]
Is the dtc binary that you use compiled from the source code here: https://git.kernel.org/pub/scm/utils/dtc/dtc.git ?

**Comment by PeterSuh-Q3** [comment]
Sorry for the late reply.
As you can see, the version of DTC used in XPE has been confirmed to be v1.6.1.

I never compiled it myself, and I think pocopico was probably still using the imported dtc binary.

------------------------------------------------------------------------

SynologyNAS login: root

Synology strongly advises you not to run commands as the root user, who has
the highest privileges on the system. Doing so may cause major damages
to the system. Please note that if you choose to proceed, all consequences are
at your own risk.

BusyBox v1.30.1 () built-in shell (ash)

SynologyNAS> dtc --version
Version: DTC 1.6.1-gc001fc01-dirty
SynologyNAS>
