### ISSUE TITLE
Planned update to syno_hdd_db script

### ISSUE THREAD

**Issue by 007revad** [PeterSuh-Q3/tcrp-addons#5]
@PeterSuh-Q3 

I was about to add the following to my scripts, but I remembered XPE loaders use /opt/bin or /opt/sbin

Will this cause issues for XPE users?
```
# Prevent Entware or user edited PATH causing issues
export PATH=$(echo "$PATH" | sed -e 's/\/opt\/bin:\/opt\/sbin://')
```

**Comment by PeterSuh-Q3** [comment]
> @PeterSuh-Q3
> 
> I was about to add the following to my scripts, but I remembered XPE loaders use /opt/bin or /opt/sbin
> 
> Will this cause issues for XPE users?
> 
> ```
> # Prevent Entware or user edited PATH causing issues
> export PATH=$(echo "$PATH" | sed -e 's/\/opt\/bin:\/opt\/sbin://')
> ```


This looks like a script designed for users who already have Entware installed on their DSM.

In Synology's junior level, /opt doesn't exist.
I think Entware forces the creation of the /opt/ folder, right?
Did Synology have this /opt folder already?

<img width="646" alt="스크린샷 2024-10-22 오후 3 54 18" src="https://github.com/user-attachments/assets/284447ad-7015-4952-af03-8dbf4c5cf10d">

**Comment by 007revad** [comment]
Thanks.

You're right. DSM does not have the /opt folder, unless something creates it.

All 3 of my Synology NAS have the /opt folder but it only contains empty folders (that appear to have been created by Docker/Container Manager).
```
/opt
/opt/containerd
/opt/containerd/bin
/opt/containerd/lib
```
